"""
Core Interfaces for the Voice Assistant.

This module defines the abstract base classes (ABCs) that establish the contract
for all hardware components and machine learning models in the system. By programming
to these interfaces, the orchestrator (ConversationManager) remains decoupled from
specific implementations (e.g., Whisper, Kokoro, OpenAI).
"""
# Path: core/interfaces.py
from abc import ABC, abstractmethod
from typing import Any, Iterator, Optional, Callable
import threading

class IAudioInput(ABC):
    """Interface for capturing audio from an input source (e.g., Microphone)."""
    
    @abstractmethod
    def capture_audio(
        self, 
        on_speech_started: Optional[Callable] = None, 
        abort_event: Optional[threading.Event] = None, 
        silence_timeout: Optional[float] = None, 
        vad_threshold: float = 1.5
    ) -> Optional[bytes]:
        """
        Captures audio data from the input source.

        Args:
            on_speech_started (Optional[Callable]): Callback triggered when VAD detects speech.
            abort_event (Optional[threading.Event]): Event to immediately halt recording if set (e.g., for barge-in).
            silence_timeout (Optional[float]): Maximum seconds of silence to tolerate before timing out.
            vad_threshold (float): Sensitivity threshold for detecting human speech.

        Returns:
            Optional[bytes]: The captured raw audio data, or None if no speech was detected.
        """
        pass

class IAudioOutput(ABC):
    """Interface for playing audio back to the user (e.g., Speakers, Headphones)."""
    
    @abstractmethod
    def play_audio(self, audio_data: bytes) -> None:
        """
        Plays a single, contiguous block of raw audio data.

        Args:
            audio_data (bytes): The raw audio bytes to play.
        """
        pass

    @abstractmethod
    def play_stream(self, audio_chunks: Iterator[bytes], cancel_event: Optional[threading.Event] = None) -> None:
        """
        Plays a continuous stream of audio chunks.

        Args:
            audio_chunks (Iterator[bytes]): An iterator yielding raw audio bytes (e.g., from a TTS engine).
            cancel_event (Optional[threading.Event]): If set, immediately stops playing the stream.
        """
        pass

class ISTTModel(ABC):
    """Interface for Speech-to-Text (STT) transcription models."""
    
    @abstractmethod
    def transcribe(self, audio_data: bytes) -> str:
        """
        Converts raw audio bytes into text.

        Args:
            audio_data (bytes): The raw audio data captured from the microphone.

        Returns:
            str: The transcribed text.
        """
        pass

class ILLMModel(ABC):
    """Interface for Large Language Models (LLM) handling conversational logic."""
    
    @abstractmethod
    def generate_response(self, text: str) -> Iterator[str]:
        """
        Generates a streaming text response to user input.

        Args:
            text (str): The user's spoken input transcribed as text.

        Yields:
            str: Tokens or text chunks generated by the language model.
        """
        pass

    @abstractmethod
    def generate_proactive_response(self, system_note: str) -> Iterator[str]:
        """
        Generates a streaming text response triggered by the system (e.g., timeouts, nudges).

        Args:
            system_note (str): Internal prompt detailing the situation.

        Yields:
            str: Tokens or text chunks generated by the language model.
        """
        pass

    @abstractmethod
    def save_profile(self, new_summary: str, new_goal: Optional[str] = None) -> None:
        """
        Persists user state, summaries, or goals to short/long-term memory.

        Args:
            new_summary (str): The latest summary of the conversation.
            new_goal (Optional[str]): A specific goal the user wants to achieve.
        """
        pass

class ITTSModel(ABC):
    """Interface for Text-to-Speech (TTS) synthesis models."""
    
    @abstractmethod
    def synthesize(self, text: str, speed: float = 1.0) -> Iterator[bytes]:
        """
        Synthesizes text into a stream of audio bytes.

        Args:
            text (str): The text string to vocalize.
            speed (float): The speed multiplier for the generated speech (1.0 is normal).

        Yields:
            bytes: Chunks of synthesized audio data.
        """
        pass